layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: Apoorva Krishnamurthy
  # linkedin: Apoorva Krishnamurthy
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: Apoorva Krishnamurthy
  # youtube: your_username
  # vk: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/css
    image_url: https://1y2f7khiqam2m680tzdbhekr-wpengine.netdna-ssl.com/wp-content/uploads/ml-icon.png

  - name: App development
    image_url: http://chittagongit.com/download/305998

  - name: Competitive programming
    web_url: https://github.com/topics/sass
    image_url: http://myweb.students.wwu.edu/trieuh/360/PROJECT%202%20CODE/images/trophy-icon.png
